eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8700/eureka/
  instance:
    hostname: localhost
    
microservice:
  pssService:
    endpoints:
      endpoint:
        uri: http://PSS-SERVICE/pss/flight/findFlight
